# Generated by Django 5.1.2 on 2024-11-16 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maoweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=20)),
                ('ident_emp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=20)),
                ('medio_pago', models.CharField(max_length=20)),
                ('fecha', models.CharField(max_length=20)),
                ('numero_recibo', models.CharField(max_length=20)),
                ('monto', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=130)),
                ('id_usuario', models.CharField(max_length=30)),
                ('sede', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_gasto', models.CharField(max_length=120)),
                ('valor', models.CharField(max_length=20)),
                ('iva', models.CharField(max_length=20)),
                ('gastos_sede', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='premios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=20)),
                ('premio', models.CharField(max_length=20)),
                ('Desc_premio', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=20)),
                ('sede_proveedor', models.CharField(max_length=20)),
                ('precio', models.CharField(max_length=20)),
                ('representante', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='puntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_conductor', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=20)),
                ('v_ident', models.CharField(max_length=20)),
                ('cantidad', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='conductor',
            name='email_cond',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conductor',
            name='fidelidad',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conductor',
            name='ident_cond',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conductor',
            name='telefono_cond',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='Salario',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='contrato',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='emp_email',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='especialidad',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='experiencia',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='ident_emp',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sede',
            name='administrador_sede',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sede',
            name='gastos_sede',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sede',
            name='horario',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sede',
            name='id_sede',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sede',
            name='sede_proveedor',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='soat',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='v_ident',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='vias_frecuentes',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='edad_empleado',
            field=models.CharField(max_length=60),
        ),
    ]
